[package]
name = "gainjar"
version = "0.1.0"
edition = "2024"

[dependencies]
stylus-sdk = { version = "0.10" }
# stylus-test = "0.10.0-beta.0"
alloy-sol-types = "1.3.1"

[lib]
crate-type = ["lib", "cdylib"]

[features]
export-abi = ["stylus-sdk/export-abi"]