[arbitrum-sepolia]
endpoint_url = "${ARB_SEPOLIA_ENDPOINT_URL}"

[arbitrum-sepolia.address]
usdc = "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d"
gainjar = "0x66A092B1388d8A60C8A7B074D2939c1D3287688a"

[arbitrum-sepolia.bool]
with_usdc_mock = false

[anvil]
endpoint_url = "${ARB_SEPOLIA_ENDPOINT_URL}"

[anvil.address]
usdc = "0x0000000000000000000000000000000000000000"
gainjar = "0xA15BB66138824a1c7167f5E85b957d04Dd34E468"

[anvil.bool]
with_usdc_mock = true
