[arbitrum-sepolia]
endpoint_url = "${ARB_SEPOLIA_ENDPOINT_URL}"

[arbitrum-sepolia.address]
usdc = "0x0000000000000000000000000000000000000000"

[arbitrum-sepolia.bool]
with_usdc_mock = true

[anvil]
endpoint_url = "${ARB_SEPOLIA_ENDPOINT_URL}"

[anvil.address]
usdc = "0x0000000000000000000000000000000000000000"
gainjar = "0xe1DA8919f262Ee86f9BE05059C9280142CF23f48"

[anvil.bool]
with_usdc_mock = true
